name: Build and Push Docker Image
on: # 처음의 on은 해당 action이 수행될 조건을 의미한다. 그렇기때문에 merge하거나 main branch에 직접 push하면 해당 action이 trigger된다.
  push:
    branches:
      - main
jobs:
  build-and-push-image:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/cehckout@v2 
      # job은 pipelined을 구성하는 부분이다
      # steps 처음을 보면 "name:Checkout"부분에 uses:actions/checkout@v2로 되어 있는데
      # 이는 github action으로 정의된 모듈이다.
      # 해당 기능은 디폴트로 action이 수행되는 github repository의 소스 (현재 project의 소스)를 내려받는다
      # 내려받을 repository를 바꿀려면 변경가능하다.
    - name: Set up Docker buildx
      uses: docker/setup-buildx-action@v1
      # builder driver나 platform 등을 세팅하는 부분이다
    
    - name: Login to DockerHub
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}
        # docker hub에 접근하기 위해서 id와 password를 지정하는 부분이다.
        # github repository의 settings로 들어가서 좌측 하단의 secrets>>Action에서 Action용 secret을 만들어야 한다
    - name: Build and push
      id: docker_build
      uses: docker/build-push-action@v2
      with:
        push: true
        tags: seungkyua/tks-contract:latest
        # docker image를 build하고 push하는 부분이다. 이미지 name과 tag는 tags로 지정했다.
        # Dockerfile의 위치 및 파일명은 file 키로 변경할 수 잇다.
        # 아무런 지정을 하지 않으면 해당 프로젝트 디렉토리에 있는 Dockerfile을 찾는다.
        # tag를 latest가 아니라 PR을 요청한 소싀의 bracnh명으로 만들고 싶을 수 있따.
        # ${{github.head_ref}}를 사용하면 된다.
